version: 2.1
jobs:
  build:
    docker:
      - image: gmao/ubuntu20-geos-env-mkl:v6.2.4-openmpi_4.0.5-gcc_10.3.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_AUTH_TOKEN
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Versions etc"
          command: mpirun --version && gfortran --version && echo $BASEDIR && pwd && ls
      - run:
          name: "Echo out environment variables"
          command: |
            echo "CIRCLE_BRANCH: ${CIRCLE_BRANCH}"
            echo "CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}"
            echo "CIRCLE_PROJECT_USERNAME: ${CIRCLE_PROJECT_USERNAME}"
            echo "CIRCLE_PULL_REQUEST: ${CIRCLE_PULL_REQUEST}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
            echo "CIRCLE_TAG: ${CIRCLE_TAG}"
            echo "CIRCLE_USERNAME: ${CIRCLE_USERNAME}"
