name: Push to develop

on:
  push:
    branches:
      - develop

jobs:
  pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the action
        uses: devops-infra/action-pull-request@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: refactor
          label: automatic, refactor
          template: .github/AUTOMATIC_PR_TEMPLATE.md
          get_diff: true
          assignee: ${{ github.actor }}
          old_string: "<!-- Write your description here -->"
          new_string: ${{ github.event.commits[0].message }}
          title: ${{ github.event.commits[0].message }}

